name: Deploy to Streamlit Cloud

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9, 3.10, 3.11]

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Basic validation
      run: |
        echo "🔍 Basic validation checks..."
        echo "✅ Python version: $(python --version)"
        echo "✅ Working directory: $(pwd)"
        echo "✅ Repository contents:"
        ls -la
        
        echo "✅ Key files check:"
        if [ -f "streamlit_app_clean.py" ]; then
          echo "  ✅ Streamlit app found"
        else
          echo "  ❌ Streamlit app missing"
        fi
        
        if [ -f "requirements.txt" ]; then
          echo "  ✅ Requirements file found"
          echo "  📦 Dependencies:"
          cat requirements.txt
        else
          echo "  ❌ Requirements file missing"
        fi
        
        if [ -f "api/main.py" ]; then
          echo "  ✅ FastAPI backend found"
        else
          echo "  ❌ FastAPI backend missing"
        fi
        
        echo "✅ Basic validation completed"

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Deploy to Streamlit Cloud
      run: |
        echo "🚀 Deployment to Streamlit Cloud is automatic when pushing to main branch"
        echo "✅ Make sure your repository is connected to Streamlit Cloud"
        echo "🌐 App will be available at: https://your-app-name.streamlit.app"
        echo ""
        echo "📋 Deployment Checklist:"
        echo "  ✅ Code pushed to main branch"
        echo "  ✅ Tests passed"
        echo "  ✅ Streamlit Cloud connected"
        echo "  ✅ Auto-deployment enabled"
